# Generated by Django 3.2.5 on 2021-09-10 14:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbidconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
