# Generated by Django 3.2.5 on 2021-09-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='productbiding',
            options={'ordering': ['-created_at']},
        ),
    ]
